Automatically remind people to RSVP
codeRIT/hackathon-manager pull request #175
Opened 2019-08-14 14:28 UTC by dquach217

Fixes #18

2019-08-14 14:30 UTC, dquach217 commented
Currently Work in Progress, please do not approve as of yet

2019-08-14 19:33 UTC, dquach217 commented
@sman591 When you have the chance to, could you walk me through testing email triggers?

2019-08-14 19:42 UTC, sman591 commented
Happy to - I'll try to take a look later today or tomorrow and follow-up with some steps to test with

2019-08-20 02:36 UTC, dquach217 commented
@sman591 Make the changes as you requested.

2019-08-25 00:26 UTC, sman591 commented on app/models/user.rb
> +  end
This can be removed now that we're queueing on the questionnaire model

2019-08-25 00:45 UTC, dquach217 commented
@sman591 I think adding a test would be great, but not sure how we can replicate the actions since we would have it wait until it meets a certain criteria to be sent out

2019-08-25 00:54 UTC, sman591 commented on app/models/user.rb
> +  after_create :queue_reminder_email, :queue_rsvp_email
```suggestion
  after_create :queue_reminder_email
```

2019-08-25 01:03 UTC, sman591 submitted a review, later dismissed
For tests -- the best way to support the conditions would be to test against various `event_start_date` config values while wrapping the tests with `Timecop.freeze`

```ruby
HackathonConfig["event_start_date"] = "2020-06-15"
Timecop.freeze("2020-06-01") do
  # the tests here...
end
```

Up to you though

2019-08-25 01:09 UTC, dquach217 commented
I will try creating a bunch of tests using the suggested method. Thanks!

2020-07-31 03:40 UTC, cbaudouinjr commented
Closing as PR is too stale.

2020-09-19 23:09 UTC, peterkos commented
We'll release this as-is as part of 2.0 without the unit tests, as @cbaudouinjr has verified this functionality by hand. 
@dquach217 Is this ready to go otherwise?

2020-09-20 02:19 UTC, cbaudouinjr submitted a review, later dismissed

2020-09-20 02:37 UTC, peterkos approved these changes

2020-09-20 02:52 UTC, peterkos requested changes

2020-09-20 02:52 UTC, peterkos commented on app/models/questionnaire.rb
> +      days_remaining = Date.parse(HackathonConfig["event_start_date"]) - Time.now.to_date
Time zone bug @cbaudouinjr told you ;)

2020-09-20 03:54 UTC, peterkos requested changes

2020-09-20 03:54 UTC, peterkos commented on app/mailers/user_mailer.rb
> +    return if @user.blank? || !@user.questionnaire.acc_status == "accepted" || Time.now.to_date > Date.parse(HackathonConfig["event_start_date"])
Time zone bug 🤔

2020-09-20 04:05 UTC, peterkos approved these changes
LGTM! 🚀

2020-09-20 04:13 UTC, merged