refactor(docs): Updates Environment Variable docs
codeRIT/hackathon-manager pull request #300
Opened 2020-08-14 01:46 UTC by cbaudouinjr

- Adds a better description for environment variables
- Adds a way to contact us for help
- Separates required/recommended variables 
- Updates MyMLH verbiage

**Before**
<img width="821" alt="image" src="https://user-images.githubusercontent.com/22222538/90203226-2602ff00-ddae-11ea-9370-eaf9ddfa5faf.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/22222538/90203266-3e731980-ddae-11ea-8b4b-3407d04360b3.png">

**After**
<img width="805" alt="image" src="https://user-images.githubusercontent.com/22222538/90203322-5d71ab80-ddae-11ea-9d6b-c957efa4a835.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/22222538/90203334-682c4080-ddae-11ea-8a92-0c5193601970.png">

closes #297

2020-09-08 04:55 UTC, peterkos requested changes

2020-09-08 04:55 UTC, peterkos commented on docs/deployment-environment-variables.md
> +Various services require environment variables to operate. While they may appear overwheling, this setup guide aims to alleviate some of the concern. It is recommended you start with the required var
```suggestion
Various services require environment variables to operate. While they may appear overwhelming, this setup guide aims to alleviate some of the concern. 
```
I feel like the required/optional parts below are well laid out enough that we don't need to emphasize that

2020-09-08 04:55 UTC, peterkos commented on docs/deployment-environment-variables.md
>  ### Secret keys
These should be up by `## Required` if they are required to run?

2020-09-08 04:55 UTC, peterkos commented on docs/deployment-environment-variables.md
> +MLH_KEY="my-mlh-application-id"
Not sure why this code block is here; seems more appropriate to move it under the `MyMLH` section below?

2020-09-16 19:36 UTC, cbaudouinjr commented
Redesigned the Environment Variable page to reduce the large code blocks. Page is now designed to force the reader to read through the whole page. I also reorganized the keys based on required/optional so they'll show that way on the page navigation.

2020-09-16 19:59 UTC, peterkos requested changes

2020-09-16 19:59 UTC, peterkos commented on docs/deployment-environment-variables.md
> +## Optional
Maybe add `The following environment variables are optional` just to be consistent w/ the description under `##Required`?

2020-09-16 19:59 UTC, peterkos commented on docs/deployment-environment-variables.md
>  `SECRET_KEY_BASE` and `DEVISE_SECRET_KEY` are required for the app to run. You can generate secrets via `bundle exec rake secret`. This "secret" is a 64-byte hexadecimal string (128 characters). You
```suggestion
You can generate secrets via `bundle exec rake secret`. This "secret" is a 64-byte hexadecimal string (128 characters). You could also generate this with `head -c 64 /dev/urandom | xxd -ps -c 128` if you are on a standard Linux distribution.
```

Just to alleviate the redundancy as this is stated directly above this env var

2020-09-16 19:59 UTC, peterkos commented on docs/deployment-environment-variables.md
> +### Amazon S3 and Resumes
I appreciate adding "Amazon S3" vs just "S3"!

2020-09-16 22:45 UTC, peterkos approved these changes
:shipit:

2020-09-16 22:45 UTC, merged