Hm 382
codeRIT/hackathon-manager pull request #407
Opened 2020-11-29 01:21 UTC by clh7090

![image](https://user-images.githubusercontent.com/59103082/100529551-c8f15480-31b6-11eb-910d-c7b2d19a1847.png)
![image](https://user-images.githubusercontent.com/59103082/100529557-da3a6100-31b6-11eb-8eb6-94364d7effaf.png)
Changed 'admin' to director in README and in the Users & Staff page

2020-11-30 05:41 UTC, cbaudouinjr requested changes

2020-11-30 05:41 UTC, cbaudouinjr commented on config/locales/en.yml
> +        role: Limited access prevents the director from adding, modifying, or deleting any records; modifications through the check-in process are allowed. Event tracking limits to only event trackin
Sorry this was a little confusing, role should read: "Organizers are prevented from adding, modifying, or deleting any records; modifications through the check-in process are allowed. Volunteers only have access to the check-in process."

2020-11-30 05:42 UTC, cbaudouinjr commented
Also remember to commit using the semantic-release format! For this it'd be "refactor: Updates old role verbiage in manage area and docs"

2020-12-01 23:06 UTC, peterkos requested changes
Great start!

One thing we could do is have each role's description only show up when that role is selected in the dropdown, however that'd take some HAML `if` statements and messing around with SimpleForm if you're comfortable. 

Otherwise, we could try what I suggested in the comment with a mockup. Thoughts? @cbaudouinjr @clh7090

2020-12-15 08:55 UTC, peterkos commented
Note: change base branch before merge!

2021-02-02 05:13 UTC, peterkos commented
Moving TBA

2021-02-02 05:13 UTC, closed without merging