feat(config): added a reset button to the hackathon
codeRIT/hackathon-manager pull request #504
Opened 2021-01-02 15:26 UTC by JeremyRudman

This will delete all questionnaires and user accounts with a specified role and leave all other data intact
![image](https://user-images.githubusercontent.com/38338616/103460533-d7b2b600-4ce4-11eb-962f-c1ee26f1abe4.png)

2021-01-27 05:14 UTC, cbaudouinjr requested changes
Just a quick code review. I need to still do deep testing with audits.

2021-01-27 05:14 UTC, cbaudouinjr commented on app/controllers/manage/configs_controller.rb
> +      next if delete != 1
```suggestion
      next if delete.zero?
```

https://stackoverflow.com/questions/3534709/ruby-integer-to-boolean

2021-01-27 05:14 UTC, cbaudouinjr commented on app/views/manage/configs/index.html.haml
> +          This will delete all users and questionnaires for the selected roles
```suggestion
          This will delete all users and questionnaires for the selected roles.
```

2021-01-27 05:14 UTC, cbaudouinjr commented on app/views/manage/configs/index.html.haml
> +        %p This action is irreversible. This will delete all the questionnaires and user accounts for the roles selected
```suggestion
        %p This action is irreversible. This will delete all the questionnaires and user accounts for the roles selected.
```

2021-06-22 00:36 UTC, peterkos commented
Closing in favor of 3.0 work; written down in Notion to go back to!

2021-06-22 00:36 UTC, closed without merging