feat(schedule): add category field to schedule
codeRIT/hackathon-manager pull request #546
Opened 2021-01-25 22:49 UTC by JeremyRudman

add category option to schedule

![chrome_2021-01-25_17-42-43](https://user-images.githubusercontent.com/38338616/105775835-7a9dcf00-5f35-11eb-8c01-fbe8a15eec04.png)
![chrome_2021-01-25_17-42-36](https://user-images.githubusercontent.com/38338616/105775836-7b366580-5f35-11eb-8fe6-9dcb9bdb34ac.png)

2021-01-27 05:17 UTC, cbaudouinjr requested changes

2021-01-27 05:17 UTC, cbaudouinjr commented on db/migrate/20200529142141_create_events.rb
> +      t.string :category
This should be a new migration since the schedule is already in 2.2!

2021-01-31 23:42 UTC, JeremyRudman commented
![image](https://user-images.githubusercontent.com/38338616/106401652-4a51a700-63f3-11eb-95f7-1891b4449eb1.png)

2021-02-01 02:39 UTC, peterkos requested changes

2021-02-01 02:39 UTC, peterkos commented on app/assets/javascripts/events.js
> +      if(event.description){
```suggestion
      if(event.description) {
```

2021-02-01 02:39 UTC, peterkos approved these changes

2021-02-01 02:59 UTC, merged