feat(questionnaire): add country field for questionnaire
codeRIT/hackathon-manager pull request #550
Opened 2021-01-30 20:37 UTC by JeremyRudman

the application now asks for a country to due to MLH requirements
![chrome_2021-01-30_13-50-51](https://user-images.githubusercontent.com/38338616/106367369-236e7480-6310-11eb-9737-89b229cefa36.png)
![chrome_2021-01-30_15-32-40](https://user-images.githubusercontent.com/38338616/106367416-6fb9b480-6310-11eb-8de1-7a57b5b70cfe.png)
![image](https://user-images.githubusercontent.com/38338616/106367488-f2427400-6310-11eb-9aac-23d5c62feaa4.png)
![chrome_2021-01-30_13-56-03](https://user-images.githubusercontent.com/38338616/106367371-28cbbf00-6310-11eb-8872-d3a82b216a9f.png)

2021-01-31 23:36 UTC, JeremyRudman commented
![image](https://user-images.githubusercontent.com/38338616/106401652-4a51a700-63f3-11eb-95f7-1891b4449eb1.png)

2021-02-02 04:15 UTC, cbaudouinjr requested changes

2021-02-02 04:15 UTC, cbaudouinjr commented on app/views/application/_missing_country_notice.html.haml
> +    and specify your country
```suggestion
    and specify your country.
```

2021-02-03 05:45 UTC, peterkos approved these changes

2021-02-03 06:08 UTC, merged