fix(questionnaire): fixed whitespace and readded agreements to edit page
codeRIT/hackathon-manager pull request #582
Opened 2021-02-08 19:02 UTC by JeremyRudman

fixed the whitespace which was caused by label being a empty string instead of false so the label space was still there. The agreements were also re added although disabled for a director to change.

current:
![chrome_2021-02-08_13-41-19](https://user-images.githubusercontent.com/38338616/107268314-fc055f00-6a15-11eb-8048-28e59a23a2b9.png)

previous:
![chrome_2021-02-08_12-42-53](https://user-images.githubusercontent.com/38338616/107268393-10495c00-6a16-11eb-99e3-aa606cd6cff7.png)

possible alternative:
![chrome_2021-02-08_12-43-07](https://user-images.githubusercontent.com/38338616/107268426-1e977800-6a16-11eb-8a2f-a25e67be8745.png)

2021-02-09 02:34 UTC, cbaudouinjr requested changes

2021-02-09 02:34 UTC, cbaudouinjr commented on app/views/manage/questionnaires/_form.html.haml
> +            = f.association :agreements, as: :check_boxes, label_method: :formatted_agreement, value_method: :id, disabled: true, label: false, hint: "Only account owners can accept questionnaires"
```suggestion
            = f.association :agreements, as: :check_boxes, label_method: :formatted_agreement, value_method: :id, disabled: true, label: false, hint: "Only account owners can accept legal agreements"
```

2021-02-13 07:56 UTC, peterkos reviewed
Not showing up for me for some reason. 
1) Used old db (try with clean)
2) Migrate
3) Add two agreements 
4) Create questionnaire w/ admin account, accept agreements
4.5) Verify agreements table exists and are recorded in database
5) Go to questionnaire
6) No agreements card visible at all

2021-02-13 07:56 UTC, peterkos commented on app/views/manage/questionnaires/_form.html.haml
> +
nit: extra newline

2021-02-13 07:57 UTC, peterkos commented
Also protip [tables](https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables#creating-a-table) are great for showing multiple screenshots alongside each other 😉

2021-02-14 04:31 UTC, cbaudouinjr approved these changes

2021-02-14 04:31 UTC, merged