refactor: Manage Config Controller to API Only
codeRIT/hackathon-manager pull request #854
Opened 2021-10-18 04:50 UTC by JeremyRudman

2021-10-18 04:51 UTC, JeremyRudman commented on app/controllers/manage/configs_controller.rb
> +      render ErrorResponse.new(:config_update_agreementMustStartHTTP), status: :unprocessable_entity
not sure if the new error message is any good

2021-10-18 23:43 UTC, cbaudouinjr requested changes

2021-10-18 23:43 UTC, cbaudouinjr commented on app/controllers/manage/configs_controller.rb
> -    @config = HackathonConfig.get_all
I think we still need the index so we can get all the configs.

2021-10-18 23:43 UTC, cbaudouinjr commented on test/controllers/manage/configs_controller_test.rb
> -      get :index
This will need to be re-added if we need the index.

2021-10-22 05:43 UTC, JeremyRudman commented on app/controllers/manage/configs_controller.rb
> -    @config = HackathonConfig.get_all
re added index

2021-10-23 06:23 UTC, cbaudouinjr approved these changes

2024-02-05 01:43 UTC, closed without merging