feat: Added HorizontalGroup, VerticalGroup, and Dropdown components
codeRIT/hackathon-manager pull request #860
Opened 2021-10-27 19:20 UTC by clairegallup

Part of #762.

![image](https://user-images.githubusercontent.com/16471311/139132409-ba84b898-0bac-4779-8847-dfc8c234fc56.png)

# Contents
- Added HorizontalGroup and VerticalGroup componets
- Added Dropdown component, using slots to "wrap around" the standard select input for form compatibility

2021-10-27 19:21 UTC, skyegallup commented on frontend/components/base/Dropdown.vue
> +<template>
cry about it

2021-10-29 23:01 UTC, peterkos requested changes
Also, nit: needs `cursor` and `text-select: none` so on hover it doesn't go text select mode :)

2021-10-29 23:01 UTC, peterkos commented on frontend/components/base/Dropdown.vue
> +        &:hover {
Keeping with the UX conventions we have, I think this should really be a color change instead of getting rid of the shadow -- see `<button>`.

So, `&:hover` (also for subitems) would change background color, and `&:active` would get rid of the shadow, "pressing" the button

2021-10-29 23:01 UTC, peterkos commented on frontend/components/base/Dropdown.vue
> +    &:not(.opened) .name {
Nice semantics!

2021-10-29 23:54 UTC, peterkos approved these changes
LGTM! Nice changes :)

2021-10-30 00:08 UTC, merged