feat: Application page
codeRIT/hackathon-manager pull request #868
Opened 2021-11-15 19:10 UTC by clairegallup

Closes #864 

# Changes
- Added Application page with all sub-pages
- Added proper labels to Dropdown, TextArea
- Removed old test navigation

2021-11-16 00:51 UTC, clairegallup commented on frontend/routes/Application.vue
> +<template>
cope

2021-11-16 00:51 UTC, clairegallup commented on frontend/routes/application/AccessibilityPage.vue
> +<template>
seethe

2021-11-16 00:51 UTC, clairegallup commented on frontend/routes/application/AgreementsPage.vue
> +<template>
mald

2021-11-16 00:51 UTC, clairegallup commented on frontend/routes/application/ApplicationPage.vue
> +<template>
don't care didn't ask

2021-11-16 00:51 UTC, clairegallup commented on frontend/routes/application/PersonalInfoPage.vue
> +<template>
ok and

2021-11-16 01:29 UTC, peterkos requested changes
Great work!
This is some good scaffolding for the Application page. But two main things that need to be done:
1. Design tweaks 
2. Model hookup (might wait for different PR?)

Creating the model is prob best left until after the design tweaks as we can use this hardcoded stuff to test it out visually.

Design wise I'll get back to you with some Figma scaffolding soon(tm). Some brief pointers:
- Additional padding between questions; think like table cell styling
    - (maybe even a soft dividing line between questions)
- More pronounced hierarchy in question font vs. question response options (see at end of comment for example [0])
- Previous button on bottom right
- Potentially also duplicating prev/next buttons on top-right? 

Some other nits + followups:
- Dropdowns need work but will be covered in another PR, brief notes:
    - Left align instead of right
    - Dropdown items should not affect page layout (see default HTML dropdown)
    - Triangle or some sort of indicator that it is a dropdown instead of a buton
    - A brief animation would be nice but we can obvs rethink that down the road more cohesively


## Preview
[0] 
<img width="826" alt="CleanShot 2021-11-15 at 20 28 32@2x" src="https://user-images.githubusercontent.com/2782749/141879190-1cda1d30-08b7-441d-9965-7e7c16b4cb7a.png">

2021-11-16 01:29 UTC, peterkos commented on frontend/components/base/Button.vue
> +    <button class="button" @click="onclick()">{{ content }}</button>
Ah yeah, this would be helpful 😅

2021-11-16 01:29 UTC, peterkos commented on frontend/App.vue
> -            <router-link class="router-link" to="/manage">Manage</router-link>
Let's make sure we get these hooked up soon!
When #865 is merged, can we add a link from `/profile` into `/manage` just hardcoded for now?

2021-11-16 16:25 UTC, clairegallup commented on frontend/components/base/Button.vue
> +    <button class="button" @click="onclick()">{{ content }}</button>
:-P

2021-11-16 16:39 UTC, clairegallup commented
> Creating the model is prob best left until after the design tweaks as we can use this hardcoded stuff to test it out visually.

I agree; model hookup can be done in the next PR, especially since it'll probably require more form input work.

> Design wise I'll get back to you with some Figma scaffolding soon(tm). Some brief pointers:
>  - Additional padding between questions; think like table cell styling
>     -  (maybe even a soft dividing line between questions)
>   - More pronounced hierarchy in question font vs. question response options (see at end of comment for example [0])
>   - Previous button on bottom right
>   - Potentially also duplicating prev/next buttons on top-right?

Good ideas! I like the preview you gave. I can add that in this PR today, unless you want me to wait for a Figma prototype.

> Some other nits + followups:
> - Dropdowns need work but will be covered in another PR, brief notes:
>    - Left align instead of right

This is fixed in this PR. You might need to dump your `.parcel-cache` again to see it.

>    - Dropdown items should not affect page layout (see default HTML dropdown)

Agreed, but it'll have to be in a separate PR because it'll take a fair bit of work.

>    - Triangle or some sort of indicator that it is a dropdown instead of a buton

Will do once I implement FontAwesome icons (which should happen ASAP, to be honest).

>    - A brief animation would be nice but we can obvs rethink that down the road more cohesively

An animation could be nice, but it's certainly lower priority than anything else here.

---

tl;dr:
- Will fix design in this PR
- Future PR priority list:
  - FontAwesome icons (for dropdown open/collapse arrow)
  - Application model to back this form
  - Fix dropdown shifting page layout

2021-11-20 01:19 UTC, clairegallup commented
![image](https://user-images.githubusercontent.com/16471311/142709159-33062b4a-54c2-4b35-ab58-15d5101ae1b8.png)

Only requested style fix that I didn't implement is adding prev/next buttons to top-right, but now that I'm thinking about it, I feel like they aren't relevant. Either the user is at the bottom of the page, where they can already see prev/next buttons, or they're at the top of the page, where they can just select the prev/next item in the application navbar.

2021-12-07 00:40 UTC, peterkos approved these changes
LGTM! Great work :smile:

2021-12-07 00:41 UTC, merged